=== statisticsnorway/microdata-validator/tests/resources/components/unit_type_variable_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
      "dateType": {
        "$comment": "Type for the date format YYYY-MM-DD. (Python package jsonschema missing support for JSON Schema date format.)",
        "type": "string",
        "pattern": "^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$"
      },
      "multilingualStringType": {
        "$comment": "Type for language support.",
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "languageCode": {
              "type": "string",
              "enum": [
                "no",
                "nb",
                "nn",
                "en"
              ]
            },
            "value": {
              "type": "string"
            }
          },
          "required": [
            "languageCode",
            "value"
          ]
        }
      },
      "codeListType": {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "categoryTitle": {
              "$ref": "#/definitions/multilingualStringType"
            },
            "validFrom": {
              "$ref": "#/definitions/dateType"
            },
            "validUntil": {
                "oneOf": [
                    {"type": "null"},
                    {"$ref": "#/definitions/dateType"}
                ]
            }
          },
          "required": [
            "code",
            "categoryTitle",
            "validFrom"
          ]
        }
      },
      "sentinelAndMissingValuesType": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "categoryTitle": {
              "$ref": "#/definitions/multilingualStringType"
            },
            "codeType": {
              "type": "string",
              "enum": [
                "MISSING",
                "SENTINEL"
              ]
            }
          },
          "required": [
            "code",
            "categoryTitle"
          ]
        }
      },
      "valueDomainType": {
        "type": "object",
        "properties": {
          "description": {
            "$ref": "#/definitions/multilingualStringType"
          },
          "measurementType": {
            "type": "string",
            "enum": [
              "CURRENCY",
              "WEIGHT",
              "LENGTH",
              "HEIGHT",
              "GEOGRAPHICAL"
            ]
          },
          "measurementUnitDescription": {
            "$ref": "#/definitions/multilingualStringType"
          },
          "uriDefinition": {
            "type": "array",
            "items": [
              {
                "type": [
                  "string",
                  "null"
                ]
              }
            ]
          },
          "codeList": {
            "$ref": "#/definitions/codeListType"
          },
          "sentinelAndMissingValues": {
            "$ref": "#/definitions/sentinelAndMissingValuesType"
          }
        },
        "anyOf": [
          {
            "required": [
              "codeList"
            ]
          },
          {
            "required": [
              "description"
            ]
          }
        ]
      }
    },
  
    "type": "object",
    "properties": {
        "shortName": {"type": "string"},
        "name": {"$ref": "#/definitions/multilingualStringType"},
        "description": {"$ref": "#/definitions/multilingualStringType"},
        "dataType": {
            "type": "string",
            "enum": ["STRING", "LONG", "DATE", "DOUBLE"]
        },
        "format": {"type": "string"},
        "unitType": {
            "type": "object",
            "properties": {
                "shortName": {"type": "string"},
                "name": {"$ref": "#/definitions/multilingualStringType"},
                "pseudonymized": {"type": "boolean"},
                "description": {"$ref": "#/definitions/multilingualStringType"}
            },
            "required": ["shortName", "name", "pseudonymized", "description"]
        },
        "valueDomain": {"$ref": "#/definitions/valueDomainType"}
    },
    "required": [
        "shortName",
        "name",
        "description",
        "dataType",
        "unitType",
        "valueDomain"
    ]
}

=== statisticsnorway/microdata-validator/microdata_validator/components/unit_type_variables/VIRKSOMHET.json
{
  "shortName": "VIRKSOMHET_ID",
  "name": [
    {
      "languageCode": "no",
      "value": "Virksomhetsidentifikator"
    },
    {
      "languageCode": "en",
      "value": "Business identifier"
    }
  ],
  "description": [
    {
      "languageCode": "no",
      "value": "Identifikator for virksomhet i Microdata"
    },
    {
      "languageCode": "en",
      "value": "Identifier for business in Microdata"
    }
  ],
  "dataType": "LONG",
  "unitType": {
    "pseudonymized": true,
    "shortName": "VIRKSOMHET",
    "name": [
      {
        "languageCode": "no",
        "value": "Virksomhet"
      },
      {
        "languageCode": "en",
        "value": "Business"
      }
    ],
    "description": [
      {
        "languageCode": "no",
        "value": "Virksomhet/bedrift er definert som en lokalt avgrenset funksjonell enhet som hovedsakelig driver virksomhet innenfor en bestemt næringsgruppe (Standard for næringsgruppering)."
      },
      {
        "languageCode": "en",
        "value": ""
      }
    ]
  },
  "format": "RandomUInt48",
  "valueDomain": {
    "description": [
      {
        "languageCode": "no",
        "value": "Pseudonymisert organisasjonsnummer"
      },
      {
        "languageCode": "en",
        "value": "Pseudonymized organisasjonsnummer"
      }
    ]
  }
}

=== statisticsnorway/microdata-validator/microdata_validator/components/unit_type_variables/FORETAK.json
{
  "shortName": "FORETAK_ID",
  "name": [
    {
      "languageCode": "no",
      "value": "Foretaksidentifikator"
    },
    {
      "languageCode": "en",
      "value": "Enterprise identifier"
    }
  ],
  "description": [
    {
      "languageCode": "no",
      "value": "Identifikator for foretak i Microdata"
    },
    {
      "languageCode": "en",
      "value": "Identifier for enterprise in Microdata"
    }
  ],
  "dataType": "LONG",
  "unitType": {
    "shortName": "FORETAK",
    "pseudonymized": true,
    "name": [
      {
        "languageCode": "no",
        "value": "Foretak"
      },
      {
        "languageCode": "en",
        "value": "Enterprise"
      }
    ],
    "description": [
      {
        "languageCode": "no",
        "value": "Virksomhet/bedrift er definert som en lokalt avgrenset funksjonell enhet som hovedsakelig driver virksomhet innenfor en bestemt næringsgruppe (Standard for næringsgruppering)."
      },
      {
        "languageCode": "en",
        "value": ""
      }
    ]
  },
  "format": "RandomUInt48",
  "valueDomain": {
    "description": [
      {
        "languageCode": "no",
        "value": "Pseudonymisert organisasjonsnummer"
      },
      {
        "languageCode": "en",
        "value": "Pseudonymized organisasjonsnummer"
      }
    ]
  }
}

=== statisticsnorway/microdata-validator/microdata_validator/components/unit_type_variables/PERSON.json
{
  "shortName": "PERSONID_1",
  "name": [
    {
      "languageCode": "no",
      "value": "Personidentifikator"
    },
    {
      "languageCode": "en",
      "value": "Person identifier"
    }
  ],
  "description": [
    {
      "languageCode": "no",
      "value": "Identifikator for person i Microdata"
    },
    {
      "languageCode": "en",
      "value": "Identifier for person in Microdata"
    }
  ],
  "dataType": "LONG",
  "unitType": {
    "shortName": "PERSON",
    "pseudonymized": true,
    "name": [
      {
        "languageCode": "no",
        "value": "Person"
      },
      {
        "languageCode": "en",
        "value": "Person"
      }
    ],
    "description": [
      {
        "languageCode": "no",
        "value": "Statistisk enhet er person (individ, enkeltmenneske)"
      },
      {
        "languageCode": "en",
        "value": "Statistical unit is person (individual person)"
      }
    ]
  },
  "format": "RandomUInt48",
  "valueDomain": {
    "description": [
      {
        "languageCode": "no",
        "value": "Pseudonymisert personnummer"
      },
      {
        "languageCode": "en",
        "value": "Pseudonymized personnummer"
      }
    ]
  }
}

=== statisticsnorway/microdata-validator/microdata_validator/components/unit_type_variables/FAMILIE.json
{
  "shortName": "FAMILIE_ID",
  "name": [
    {
      "languageCode": "no",
      "value": "Familieidentifikator"
    },
    {
      "languageCode": "en",
      "value": "Family identifier"
    }
  ],
  "description": [
    {
      "languageCode": "no",
      "value": "Identifikator for familie i Microdata"
    },
    {
      "languageCode": "en",
      "value": "Identifier for family in Microdata"
    }
  ],
  "dataType": "LONG",
  "unitType": {
    "shortName": "FAMILIE",
    "pseudonymized": true,
    "name": [
      {
        "languageCode": "no",
        "value": "Familie"
      },
      {
        "languageCode": "en",
        "value": "Family"
      }
    ],
    "description": [
      {
        "languageCode": "no",
        "value": "En familie består av personer som er fast bosatt i samme bolig, og som er knyttet til hverandre som ektefeller, samboere, registrerte partnere og/eller som foreldre og ugifte barn (uansett det ugifte barnets alder). En familie kan høyst bestå av to (påfølgende) generasjoner, og kun ett ektepar/partnerskap/samboerpar. Som familie regnes også enkeltpersoner, slik at alle personer er med i en familie og en husholdning, enten sammen med andre personer, eller alene."
      },
      {
        "languageCode": "en",
        "value": "A family is made up of persons that are permanent residents in the same household, and are connected to each other through marriage, registered partnership and/or as parents with unmarried children (regardless of the unmarried childs age). A family can include a maximum of two (subsequent) generations, and only one marriage/partnership. All individual persons are a member of a family and a houshold, so a single person is also considered a family."
      }
    ]
  },
  "format": "RandomUInt48",
  "valueDomain": {
    "description": [
      {
        "languageCode": "no",
        "value": "Pseudonymisert personnummer"
      },
      {
        "languageCode": "en",
        "value": "Pseudonymized personnummer"
      }
    ]
  }
}
