=== statisticsnorway/microdata-validator/microdata_validator/DatasetMetadataSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",

    "definitions": {
        "dateType": {
            "$comment": "Type for the date format YYYY-MM-DD. (Python package jsonschema missing support for JSON Schema date format.)",
            "type": "string", 
            "pattern": "^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$"
        },

        "multilingualStringType": {
            "$comment": "Type for language support.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "languageCode": {"type": "string",
                        "enum": ["no", "nb", "nn", "en"]},
                    "value": {"type": "string"}
                },
                "required": [
                    "languageCode",
                    "value"
                ]
            }
        },

        "codeListType": {
            "type": "object",
            "properties": {
                "codeItems": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "code": {"type": "string"},
                            "categoryTitle": {"$ref": "#/definitions/multilingualStringType"},
                            "validFrom": {"$ref": "#/definitions/dateType"},
                            "validUntil": {"$ref": "#/definitions/dateType"}
                        },
                        "required": [
                            "code",
                            "categoryTitle",
                            "validFrom"
                        ]
                    }
                }
            },
            "required": [
                "codeItems"
            ]
        },

        "sentinelAndMissingValuesType": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "code": {"type": "string"},
                    "categoryTitle": {"$ref": "#/definitions/multilingualStringType"},
                    "codeType": {"type": "string",
                        "enum": ["MISSING", "SENTINEL"]
                    }
                },
                "required": [
                    "code",
                    "categoryTitle"
                ]
            }
        },

        "valueDomainType": {
            "type": "object",
            "properties": {
                "description": {"$ref": "#/definitions/multilingualStringType"},
                "measurementType": {"type": "string",
                    "enum": ["CURRENCY", "WEIGHT", "LENGTH", "HEIGHT", "GEOGRAPHICAL"]
                },
                "measurementUnitDescription": {"$ref": "#/definitions/multilingualStringType"},
                "uriDefinition": {
                    "type": "array",
                    "items": [
                        {"type": [ "string", "null" ]}
                    ]
                },
                "codeList": {"$ref": "#/definitions/codeListType"},
                "sentinelAndMissingValues": {"$ref": "#/definitions/sentinelAndMissingValuesType"}
            },
            "required": [
                "description"
            ]
        },

        "unitTypeType": {
            "type": "object",
            "properties": {
                "shortName": {"type": "string"},
                "name": {"$ref": "#/definitions/multilingualStringType"},
                "description": {"$ref": "#/definitions/multilingualStringType"}
            },
            "required": [
                "shortName",
                "name",
                "description"
            ]
        },

        "subjectFieldsType": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "shortName": {"type": "string"},
                        "name": {"$ref": "#/definitions/multilingualStringType"},
                        "description": {"$ref": "#/definitions/multilingualStringType"}
                    },
                    "required": [
                        "shortName",
                        "name",
                        "description"
                    ]
                }
            ]
        }
    },

    
    "type": "object",
    "properties": {
        "shortName": {"type": "string"},
        "temporalityType": {"type": "string",
            "enum": ["FIXED", "STATUS", "ACCUMULATED", "EVENT"]
        },
        "populationDescription": {"$ref": "#/definitions/multilingualStringType"},
        "spatialCoverageDescription": {"$ref": "#/definitions/multilingualStringType"},
        "dataRevision": {
            "type": "object",
            "properties": {
                "description": {"$ref": "#/definitions/multilingualStringType"},
                "temporalEndOfSeries": {"type": "boolean"}
            },
            "required": [
                "description",
                "temporalEndOfSeries"
            ]
        },
        "identifierVariables": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "shortName": {"type": "string"},
                    "name": {"$ref": "#/definitions/multilingualStringType"},
                    "description": {"$ref": "#/definitions/multilingualStringType"},
                    "dataType": {"type": "string", "enum": ["STRING", "LONG"]},
                    "unitType": {"$ref": "#/definitions/unitTypeType"},
                    "valueDomain": {"$ref": "#/definitions/valueDomainType"},
                    "uriDefinition": {
                        "type": "array",
                        "items": {"type": ["string", "null"] }
                    },
                    "format": {
                        "type": "string",
                        "$comment": "E.g. a regular expression or a specific type like RandomUInt48."
                    }
                },
                "required": [
                    "shortName",
                    "name",
                    "description",
                    "dataType",
                    "valueDomain",
                    "unitType"
                ]
            }
        },
        "measureVariables": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "shortName": {"type": "string"},
                    "name": {"$ref": "#/definitions/multilingualStringType"},
                    "description": {"$ref": "#/definitions/multilingualStringType"},
                    "dataType": {"type": "string", "enum": ["STRING", "LONG", "DATE", "DOUBLE"]},
                    "unitType": {"$ref": "#/definitions/unitTypeType"},
                    "valueDomain": {"$ref": "#/definitions/valueDomainType"},
                    "subjectFields": {"$ref": "#/definitions/subjectFieldsType"},
                    "uriDefinition": {
                        "type": "array",
                        "items": {"type": ["string", "null"] }
                    },
                    "format": {
                        "type": "string",
                        "$comment": "E.g. a regular expression or a specific type like RandomUInt48."
                    }
                },
                "required": [
                    "shortName",
                    "name",
                    "description",
                    "dataType",
                    "valueDomain"
                ]
            }
        },
        "attributeVariables": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "variableRole": {"type": "string",
                        "enum": ["START_TIME", "STOP_TIME", "ATTRIBUTE"]
                    },
                    "shortName": {"type": "string"},
                    "name": {"$ref": "#/definitions/multilingualStringType"},
                    "description": {"$ref": "#/definitions/multilingualStringType"},
                    "dataType": {"type": "string",
                        "enum": ["STRING", "LONG", "DOUBLE", "DATE"]
                    },
                    "uriDefinition": {
                        "type": "array",
                        "items": {"type": ["string", "null"] }
                    },
                    "format": {
                        "type": "string",
                        "$comment": "E.g. a regular expression or a specific type like RandomUInt48."
                    }
                },
                "required": [
                    "variableRole",
                    "shortName",
                    "name",
                    "description",
                    "dataType"
                ]
            }
        }
    },
    "required": [
        "shortName",
        "temporalityType",
        "populationDescription",
        "identifierVariables",
        "measureVariables",
        "attributeVariables",
        "spatialCoverageDescription",
        "dataRevision"
    ]
}

=== statisticsnorway/microdata-validator/tests/resources/expected/SYNT_PERSON_INNTEKT.json
{
    "shortName": "SYNT_PERSON_INNTEKT",
    "temporalityType": "ACCUMULATED",
    "populationDescription": [
        {
            "languageCode": "no",
            "value": "Alle rapporterte personinntekter i norge fra \u00e5r 1234 til \u00e5r 4321"
        }
    ],
    "spatialCoverageDescription": [
        {
            "languageCode": "no",
            "value": "Norge"
        }
    ],
    "dataRevision": {
        "description": [
            {
                "languageCode": "no",
                "value": "F\u00f8rste publisering."
            }
        ],
        "temporalEndOfSeries": false,
        "temporalCoverageStart": "1970-01-01",
        "temporalCoverageLatest": "2020-12-31"
    },
    "identifierVariables": [
        {
            "shortName": "PERSONID_1",
            "name": [
                {
                    "languageCode": "no",
                    "value": "Personidentifikator"
                }
            ],
            "description": [
                {
                    "languageCode": "no",
                    "value": "Identifikator for person i Microdata"
                }
            ],
            "dataType": "STRING",
            "unitType": {
                "shortName": "PERSON",
                "name": [
                    {
                        "languageCode": "no",
                        "value": "Person"
                    }
                ],
                "description": [
                    {
                        "languageCode": "no",
                        "value": "Statistisk enhet er person (individ, enkeltmenenske)"
                    }
                ]
            },
            "format": "RandomUInt48",
            "valueDomain": {
                "shortName": "PERSONID_1",
                "description": [
                    {
                        "languageCode": "no",
                        "value": "Pseudonymisert personnummer"
                    }
                ]
            }
        }
    ],
    "measureVariables": [
        {
            "shortName": "SYNT_PERSON_INNTEKT",
            "name": [
                {
                    "languageCode": "no",
                    "value": "Personens inntekt"
                }
            ],
            "description": [
                {
                    "languageCode": "no",
                    "value": "Personens rapporterte inntekt"
                }
            ],
            "subjectFields": [
                {
                    "shortName": "OEKONOMI",
                    "name": [
                        {
                            "languageCode": "no",
                            "value": "\u00d8konomi"
                        }
                    ],
                    "description": [
                        {
                            "languageCode": "no",
                            "value": "\u00d8konomi"
                        }
                    ]
                },
                {
                    "shortName": "SAMFUNN",
                    "name": [
                        {
                            "languageCode": "no",
                            "value": "Samfunn"
                        }
                    ],
                    "description": [
                        {
                            "languageCode": "no",
                            "value": "Samfunn"
                        }
                    ]
                }
            ],
            "dataType": "STRING",
            "uriDefinition": [
                ""
            ],
            "valueDomain": {
                "uriDefinition": [],
                "description": [
                    {
                        "languageCode": "no",
                        "value": "\u00c5rlig personinntekt"
                    }
                ],
                "measurementType": "CURRENCY",
                "measurementUnitDescription": [
                    {
                        "languageCode": "no",
                        "value": "Norske Kroner"
                    }
                ]
            }
        }
    ],
    "attributeVariables": [
        {
            "variableRole": "START_TIME",
            "shortName": "START",
            "dataType": "DATE",
            "valueDomain": {
                "description": [
                    {
                        "languageCode": "no",
                        "value": "Dato oppgitt i dager siden 1970-01-01"
                    }
                ]
            },
            "description": [
                {
                    "languageCode": "no",
                    "value": "Startdato/m\u00e5letidspunktet for hendelsen"
                },
                {
                    "languageCode": "en",
                    "value": "Startdato/m\u00e5letidspunktet for hendelsen"
                }
            ],
            "name": [
                {
                    "languageCode": "no",
                    "value": "Startdato"
                },
                {
                    "languageCode": "en",
                    "value": "Start date"
                }
            ]
        },
        {
            "variableRole": "STOP_TIME",
            "shortName": "STOP",
            "dataType": "DATE",
            "valueDomain": {
                "description": [
                    {
                        "languageCode": "no",
                        "value": "Dato oppgitt i dager siden 1970-01-01"
                    }
                ]
            },
            "description": [
                {
                    "languageCode": "no",
                    "value": "Startdato/m\u00e5letidspunktet for hendelsen"
                },
                {
                    "languageCode": "en",
                    "value": "Startdato/m\u00e5letidspunktet for hendelsen"
                }
            ],
            "name": [
                {
                    "languageCode": "no",
                    "value": "Stoppdato"
                },
                {
                    "languageCode": "en",
                    "value": "Stop date"
                }
            ]
        }
    ]
}
